Updated example test cases to show error in test application
GDATASoftwareAG/robotframework-flaui pull request #153
Opened 2024-01-26 20:18 UTC by GeoGegl

Added a test case for the Keyboard Down and Up Events labels in the test application to show an error in it. Extended existing keywords "Press key" and "Press keys" to include press and release events to enable the test.

In the test application "WpfApplication.exe" in the "Keyboard Controls" tab, the Keyboard Down Events label does not work for some keys. E.g. Arrow Keys (The Keyboard Up Events work)

2024-01-29 14:39 UTC, noubar requested changes

2024-02-03 14:19 UTC, Nepitwin requested changes
Pull request looks good. Only minimal changes must be done on robot tests. Afterwards this pr can be merged to main.

2024-02-03 14:19 UTC, Nepitwin commented on atests/Keyboard.robot
> +Check Key Up Key Down
Can you pls adjust spaces. Too many spaces are used. Pls set to arguments.

2024-02-03 14:19 UTC, Nepitwin commented on atests/Keyboard.robot
> +	FOR    ${KEY}    IN     @{KEYBOARD_KEY_LIST}
Can you pls adjust spaces. Too many spaces are used. Pls set to arguments.

2024-02-03 14:19 UTC, Nepitwin commented on atests/Keyboard.robot
> +${XPATH_LABEL_INPUT_DOWN}     ${MAIN_WINDOW_KEYBOARD_CONTROLS}/Text[@AutomationId='lblKeyboardKeyDown']
Can you pls adjust spaces. Too many spaces are used. Pls set to arguments.

2024-02-03 14:20 UTC, Nepitwin commented
@GeoGegl 

One thing do you forgot. Pls update changelog.md in root directory about parameters changes in keyboard keywords. Then all looks fine.

2024-02-05 06:22 UTC, Nepitwin approved these changes

2024-02-05 09:56 UTC, noubar approved these changes

2024-02-05 20:56 UTC, merged