further Clicks are implemented
GDATASoftwareAG/robotframework-flaui pull request #154
Opened 2024-01-30 22:05 UTC by noubar

further Clicks are implemented
click_element_identifier argument of click close changed to be an optional argument

2024-01-31 09:57 UTC, Nepitwin commented
@noubar 

Forget to update changelog

2024-01-31 10:50 UTC, noubar commented
i did not forget, the changelog is updated within the previous commit. The implementation took me two PRs because i needed your help in between.

2024-02-01 12:23 UTC, Nepitwin commented
@noubar 

Pls recheck by Keyword Mouse if Examples Are correct keywords. Common documentation is wrong keyword example

2024-02-01 12:23 UTC, Nepitwin requested changes

2024-02-01 12:23 UTC, Nepitwin commented on atests/Mouse.robot
> +/Window[@Name='FlaUI WPF Test App']/Window[@ClassName='Popup']/Menu[@ClassName='ContextMenu']/MenuItem[@Name='Context 2']
Remove it?

Missing variable usage?

2024-02-01 12:23 UTC, Nepitwin commented on src/FlaUILibrary/keywords/mouse.py
> +        | Click Open  <XPATH>  <XPATH>  |
Double Click Open

2024-02-01 12:23 UTC, Nepitwin commented on src/FlaUILibrary/keywords/mouse.py
> +        | Click Open  <XPATH>  <XPATH>  |
Right Click Open

2024-02-01 12:23 UTC, Nepitwin commented on src/FlaUILibrary/keywords/mouse.py
>          | Click Open  <XPATH>  <XPATH>  |
Click Close

2024-02-01 12:23 UTC, Nepitwin commented on src/FlaUILibrary/keywords/mouse.py
> +        | Click Open  <XPATH>  <XPATH>  |
Double Click Close

2024-02-01 12:23 UTC, Nepitwin commented on src/FlaUILibrary/keywords/mouse.py
> +        | Click Open  <XPATH>  <XPATH>  |
Right Click Close

2024-02-03 16:40 UTC, Nepitwin approved these changes

2024-02-04 12:34 UTC, merged